name:                Piccolo
version:             0.1.0.0
github:              "Selich/Piccolo"
license:             BSD3
author:              "Nikola Selic"
maintainer:          "selich.work@gmail.com"
copyright:           "Selich"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Selich/Piccolo#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  Piccolo-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Piccolo

tests:
  Piccolo-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Piccolo
